language: node_js
node_js:
  - "4"
  - "6"
services:
  - postgresql
before_script:
  - psql -c 'create database testdb;' -U postgres
before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search
